### PR TITLE
#198 warn of unexpected callable args

### LINKED ISSUE #198: Callables can only be used in certain sections
See also: https://github.com/JetBrains-Research/snakecharm/issues/187

Issue 187 only relates to lambda expressions, but similar statements hold true for any sort of callable: `input`, `group`, `resources`, `threads`, `params` can use callables, while other sections cannot.

    def params_function(wildcards, input, output, threads, resources):
        return "text"

    rule foo:
        input: "file.py"
        params: params_function
        shell: "echo hello {params}"

For example, this would work for `params`, but not for `message`.

### PR DESCRIPTION
**Pull request by SimonTsirikov**
Fixes #198

### CODE REVIEW

File: src/main/kotlin/com/jetbrains/snakecharm/inspections/SmkSectionUnexpectedCallableArgsInspection.kt [hunk 1]
```diff
@@ -0,0 +1,52 @@
+package com.jetbrains.snakecharm.inspections
```
Comment (iromeo) [inline src/main/kotlin/com/jetbrains/snakecharm/inspections/SmkSectionUnexpectedCallableArgsInspection.kt:1]: Please test your feature more attentively, at the moment doesn't work properly:

```
def params_function(wildcards, input, output, threads, resources):
    return "text"

MSG = "msg"
def conda_env(arg):
    return str(arg)

rule foo:
    conda: conda_env # here should be error
    output: MSG # here should be no error, MSG is string, not calable
    benchmark: conda_env("arg") 
    message: MSG   # here should be no error, MSG is string, not calable
    log: params_function  # here should be error
```

image

Comment (SimonTsirikov) [reply src/main/kotlin/com/jetbrains/snakecharm/inspections/SmkSectionUnexpectedCallableArgsInspection.kt:1]: I found no documentation about which sections accept callable arguments and tested it manually. It seems like in first commit including 'log' section was excess, I removed it now.
Also fixed other references false-positive warning, now it applies only to functions and lambdas.

Comment (iromeo) [reply src/main/kotlin/com/jetbrains/snakecharm/inspections/SmkSectionUnexpectedCallableArgsInspection.kt:1]: >  But section 'conda' works fine with callable, when I try it locally.
Do you launch snakemake with `--use-conda`? Otherwise, conda sections are just ignored.

Comment (iromeo) [reply src/main/kotlin/com/jetbrains/snakecharm/inspections/SmkSectionUnexpectedCallableArgsInspection.kt:1]: > I found no documentation about which sections accept callable arguments and tested it manually.

Likely it is only in snakemake sources

Comment (iromeo) [reply src/main/kotlin/com/jetbrains/snakecharm/inspections/SmkSectionUnexpectedCallableArgsInspection.kt:1]: Callable in `conda` doesn't work without/with `--use-conda`
image

Comment (iromeo) [reply src/main/kotlin/com/jetbrains/snakecharm/inspections/SmkSectionUnexpectedCallableArgsInspection.kt:1]: > which sections accept callable arguments and tested it manually

As for the list of valid/invalid section names, please see #198 and related source code investigation in #187. Also in snakemake 5.16.0 see the method  `Workflow.rule.decorate` (snakemake/workflow.py:1062). it provides assertions for different section types, e.g. direct check that `theads` and `resources` cannot be a callable. So I believe your test isn't correct.

Comment (SimonTsirikov) [reply src/main/kotlin/com/jetbrains/snakecharm/inspections/SmkSectionUnexpectedCallableArgsInspection.kt:1]: Found checkpoints for callable arguments in source code of snakemake, now PR fixed according to it.

Comment (SimonTsirikov) [reply src/main/kotlin/com/jetbrains/snakecharm/inspections/SmkSectionUnexpectedCallableArgsInspection.kt:1]: See [comment](https://github.com/JetBrains-Research/snakecharm/issues/187#issuecomment-674038509) in #187 discussion for extra information.
